# Generated by Django 4.0.3 on 2022-03-25 12:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('upload_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='chunk_number',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file',
            field=models.FileField(default=0, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
